# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

load_block_file <- function(block_file) {
    .Call(`_MR_Corr2_load_block_file`, block_file)
}

test_blocks <- function(bp, chr, block_file) {
    .Call(`_MR_Corr2_test_blocks`, bp, chr, block_file)
}

std_setdiff <- function(x, y) {
    .Call(`_MR_Corr2_std_setdiff`, x, y)
}

LDclump <- function(R, ld_r2_thresh) {
    .Call(`_MR_Corr2_LDclump`, R, ld_r2_thresh)
}

Cal_blockR <- function(bp, chr, avbIndex, idx4panel, block_file, stringname3, ld_r2_thresh, coreNum, lam) {
    .Call(`_MR_Corr2_Cal_blockR`, bp, chr, avbIndex, idx4panel, block_file, stringname3, ld_r2_thresh, coreNum, lam)
}

Cal_block_Rmatrix <- function(bp, chr, avbIndex, idx4panel, block_file, stringname3, ld_r2_thresh, coreNum, lam) {
    .Call(`_MR_Corr2_Cal_block_Rmatrix`, bp, chr, avbIndex, idx4panel, block_file, stringname3, ld_r2_thresh, coreNum, lam)
}

Cal_blockinf <- function(bp, chr, block_file) {
    .Call(`_MR_Corr2_Cal_blockinf`, bp, chr, block_file)
}

MRcorr <- function(gammah, Gammah, se1, se2, opts = NULL) {
    .Call(`_MR_Corr2_MRcorr`, gammah, Gammah, se1, se2, opts)
}

MRCorr2Sim <- function(gammah, Gammah, se1, se2, R, block_inf, coreNum, opts = NULL) {
    .Call(`_MR_Corr2_MRCorr2Sim`, gammah, Gammah, se1, se2, R, block_inf, coreNum, opts)
}

MRCorr2Real <- function(bp, chr, avbIndex, idx4panel, block_file, stringname3, ld_r2_thresh, bh1, bh2, se1, se2, lam, coreNum, opts = NULL) {
    .Call(`_MR_Corr2_MRCorr2Real`, bp, chr, avbIndex, idx4panel, block_file, stringname3, ld_r2_thresh, bh1, bh2, se1, se2, lam, coreNum, opts)
}

Cal_block_SimR <- function(block_inf, X, lam) {
    .Call(`_MR_Corr2_Cal_block_SimR`, block_inf, X, lam)
}

fastSigLm <- function(y, X) {
    .Call(`_MR_Corr2_fastSigLm`, y, X)
}

getLineNum <- function(filename) {
    .Call(`_MR_Corr2_getLineNum`, filename)
}

ReadSNPinfo <- function(stringname, A1, A2, rsname, chr, bp, morgan, N) {
    .Call(`_MR_Corr2_ReadSNPinfo`, stringname, A1, A2, rsname, chr, bp, morgan, N)
}

Read_summarystat <- function(stringname, SA1, SA2, rsname, betah, s2, pvalue, chr, bp, N) {
    invisible(.Call(`_MR_Corr2_Read_summarystat`, stringname, SA1, SA2, rsname, betah, s2, pvalue, chr, bp, N))
}

select <- function(vec_, idx_) {
    .Call(`_MR_Corr2_select`, vec_, idx_)
}

matchsnp <- function(stringname1, stringname2, stringname3, matchExp) {
    .Call(`_MR_Corr2_matchsnp`, stringname1, stringname2, stringname3, matchExp)
}

matchscreen <- function(screenname, stringname1, stringname2, stringname3, pva_cutoff, matchExp = FALSE) {
    .Call(`_MR_Corr2_matchscreen`, screenname, stringname1, stringname2, stringname3, pva_cutoff, matchExp)
}

